// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emails.sql

package db

import (
	"context"
)

const countEmailsByStatus = `-- name: CountEmailsByStatus :many
SELECT status, COUNT(*) as count FROM emails GROUP BY status
`

type CountEmailsByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountEmailsByStatus(ctx context.Context) ([]CountEmailsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countEmailsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountEmailsByStatusRow
	for rows.Next() {
		var i CountEmailsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (to_addr, from_addr, reply_to, subject, html_body, text_body, status)
VALUES (?, ?, ?, ?, ?, ?, 'pending') RETURNING id, to_addr, from_addr, reply_to, subject, html_body, text_body, status, error, created_at, sent_at
`

type CreateEmailParams struct {
	ToAddr   string
	FromAddr string
	ReplyTo  string
	Subject  string
	HtmlBody string
	TextBody string
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRowContext(ctx, createEmail,
		arg.ToAddr,
		arg.FromAddr,
		arg.ReplyTo,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.ToAddr,
		&i.FromAddr,
		&i.ReplyTo,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const getEmail = `-- name: GetEmail :one
SELECT id, to_addr, from_addr, reply_to, subject, html_body, text_body, status, error, created_at, sent_at FROM emails WHERE id = ? LIMIT 1
`

func (q *Queries) GetEmail(ctx context.Context, id int64) (Email, error) {
	row := q.db.QueryRowContext(ctx, getEmail, id)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.ToAddr,
		&i.FromAddr,
		&i.ReplyTo,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const listEmails = `-- name: ListEmails :many
SELECT id, to_addr, from_addr, reply_to, subject, html_body, text_body, status, error, created_at, sent_at FROM emails WHERE (?1 = '' OR status = ?1)
ORDER BY created_at DESC LIMIT ?3 OFFSET ?2
`

type ListEmailsParams struct {
	FilterStatus interface{}
	QueryOffset  int64
	QueryLimit   int64
}

func (q *Queries) ListEmails(ctx context.Context, arg ListEmailsParams) ([]Email, error) {
	rows, err := q.db.QueryContext(ctx, listEmails, arg.FilterStatus, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.ToAddr,
			&i.FromAddr,
			&i.ReplyTo,
			&i.Subject,
			&i.HtmlBody,
			&i.TextBody,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailFailed = `-- name: MarkEmailFailed :exec
UPDATE emails SET status = 'failed', error = ? WHERE id = ?
`

type MarkEmailFailedParams struct {
	Error string
	ID    int64
}

func (q *Queries) MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) error {
	_, err := q.db.ExecContext(ctx, markEmailFailed, arg.Error, arg.ID)
	return err
}

const markEmailSent = `-- name: MarkEmailSent :exec
UPDATE emails SET status = 'sent', sent_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) MarkEmailSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEmailSent, id)
	return err
}
