// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"time"
)

const cancelJob = `-- name: CancelJob :exec
UPDATE jobs SET status = 'cancelled' WHERE id = ? AND status = 'pending'
`

func (q *Queries) CancelJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, cancelJob, id)
	return err
}

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE jobs
SET status = 'running', attempts = attempts + 1
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'pending' AND run_at <= CURRENT_TIMESTAMP
    ORDER BY run_at ASC
    LIMIT 1
)
RETURNING id, type, payload, status, error, attempts, max_attempts, run_at, created_at
`

func (q *Queries) ClaimNextJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimNextJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.CreatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs SET status = 'done' WHERE id = ?
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeJob, id)
	return err
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT status, COUNT(*) as count FROM jobs GROUP BY status
`

type CountJobsByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountJobsByStatusRow
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (type, payload, status, run_at) VALUES (?, ?, 'pending', ?) RETURNING id, type, payload, status, error, attempts, max_attempts, run_at, created_at
`

type CreateJobParams struct {
	Type    string
	Payload string
	RunAt   time.Time
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.Type, arg.Payload, arg.RunAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.CreatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs SET status = 'failed', error = ? WHERE id = ?
`

type FailJobParams struct {
	Error string
	ID    int64
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.Error, arg.ID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, type, payload, status, error, attempts, max_attempts, run_at, created_at FROM jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.CreatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, type, payload, status, error, attempts, max_attempts, run_at, created_at FROM jobs WHERE (?1 = '' OR status = ?1)
ORDER BY created_at DESC LIMIT ?3 OFFSET ?2
`

type ListJobsParams struct {
	FilterStatus interface{}
	QueryOffset  int64
	QueryLimit   int64
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.FilterStatus, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Error,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :exec
UPDATE jobs SET status = 'pending', error = '' WHERE id = ? AND status = 'failed'
`

func (q *Queries) RetryJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, retryJob, id)
	return err
}
