// Code generated by cmd/icongen. DO NOT EDIT.

//go:generate go run github.com/omaklabs/base/cmd/icongen

package icons

import "github.com/a-h/templ"

// AlertCircle renders the Lucide "alert-circle" icon.
func AlertCircle(size string) templ.Component {
	return renderIcon(size, `<circle cx="12" cy="12" r="10"/><line x1="12" x2="12" y1="8" y2="12"/><line x1="12" x2="12.01" y1="16" y2="16"/>`)
}

// AlertTriangle renders the Lucide "alert-triangle" icon.
func AlertTriangle(size string) templ.Component {
	return renderIcon(size, `<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><line x1="12" x2="12" y1="9" y2="13"/><line x1="12" x2="12.01" y1="17" y2="17"/>`)
}

// Archive renders the Lucide "archive" icon.
func Archive(size string) templ.Component {
	return renderIcon(size, `<rect width="20" height="5" x="2" y="3" rx="1"/><path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"/><path d="M10 12h4"/>`)
}

// ArrowDown renders the Lucide "arrow-down" icon.
func ArrowDown(size string) templ.Component {
	return renderIcon(size, `<path d="M12 5v14"/><path d="m19 12-7 7-7-7"/>`)
}

// ArrowLeft renders the Lucide "arrow-left" icon.
func ArrowLeft(size string) templ.Component {
	return renderIcon(size, `<path d="m12 19-7-7 7-7"/><path d="M19 12H5"/>`)
}

// ArrowRight renders the Lucide "arrow-right" icon.
func ArrowRight(size string) templ.Component {
	return renderIcon(size, `<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>`)
}

// ArrowUp renders the Lucide "arrow-up" icon.
func ArrowUp(size string) templ.Component {
	return renderIcon(size, `<path d="m5 12 7-7 7 7"/><path d="M12 19V5"/>`)
}

// Ban renders the Lucide "ban" icon.
func Ban(size string) templ.Component {
	return renderIcon(size, `<circle cx="12" cy="12" r="10"/><path d="m4.9 4.9 14.2 14.2"/>`)
}

// Bell renders the Lucide "bell" icon.
func Bell(size string) templ.Component {
	return renderIcon(size, `<path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>`)
}

// Bookmark renders the Lucide "bookmark" icon.
func Bookmark(size string) templ.Component {
	return renderIcon(size, `<path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z"/>`)
}

// Calendar renders the Lucide "calendar" icon.
func Calendar(size string) templ.Component {
	return renderIcon(size, `<path d="M8 2v4"/><path d="M16 2v4"/><rect width="18" height="18" x="3" y="4" rx="2"/><path d="M3 10h18"/>`)
}

// Check renders the Lucide "check" icon.
func Check(size string) templ.Component {
	return renderIcon(size, `<path d="M20 6 9 17l-5-5"/>`)
}

// CheckCircle renders the Lucide "check-circle" icon.
func CheckCircle(size string) templ.Component {
	return renderIcon(size, `<path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="m9 11 3 3L22 4"/>`)
}

// ChevronDown renders the Lucide "chevron-down" icon.
func ChevronDown(size string) templ.Component {
	return renderIcon(size, `<path d="m6 9 6 6 6-6"/>`)
}

// ChevronLeft renders the Lucide "chevron-left" icon.
func ChevronLeft(size string) templ.Component {
	return renderIcon(size, `<path d="m15 18-6-6 6-6"/>`)
}

// ChevronRight renders the Lucide "chevron-right" icon.
func ChevronRight(size string) templ.Component {
	return renderIcon(size, `<path d="m9 18 6-6-6-6"/>`)
}

// ChevronUp renders the Lucide "chevron-up" icon.
func ChevronUp(size string) templ.Component {
	return renderIcon(size, `<path d="m18 15-6-6-6 6"/>`)
}

// Clipboard renders the Lucide "clipboard" icon.
func Clipboard(size string) templ.Component {
	return renderIcon(size, `<rect width="8" height="4" x="8" y="2" rx="1" ry="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/>`)
}

// Clock renders the Lucide "clock" icon.
func Clock(size string) templ.Component {
	return renderIcon(size, `<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>`)
}

// Code renders the Lucide "code" icon.
func Code(size string) templ.Component {
	return renderIcon(size, `<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>`)
}

// Columns renders the Lucide "columns" icon.
func Columns(size string) templ.Component {
	return renderIcon(size, `<rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><line x1="12" x2="12" y1="3" y2="21"/>`)
}

// Copy renders the Lucide "copy" icon.
func Copy(size string) templ.Component {
	return renderIcon(size, `<rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/>`)
}

// Database renders the Lucide "database" icon.
func Database(size string) templ.Component {
	return renderIcon(size, `<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5V19A9 3 0 0 0 21 19V5"/><path d="M3 12A9 3 0 0 0 21 12"/>`)
}

// Download renders the Lucide "download" icon.
func Download(size string) templ.Component {
	return renderIcon(size, `<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/>`)
}

// Edit renders the Lucide "edit" icon.
func Edit(size string) templ.Component {
	return renderIcon(size, `<path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"/><path d="m15 5 4 4"/>`)
}

// ExternalLink renders the Lucide "external-link" icon.
func ExternalLink(size string) templ.Component {
	return renderIcon(size, `<path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>`)
}

// Eye renders the Lucide "eye" icon.
func Eye(size string) templ.Component {
	return renderIcon(size, `<path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/>`)
}

// EyeOff renders the Lucide "eye-off" icon.
func EyeOff(size string) templ.Component {
	return renderIcon(size, `<path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49"/><path d="M14.084 14.158a3 3 0 0 1-4.242-4.242"/><path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143"/><path d="m2 2 20 20"/>`)
}

// File renders the Lucide "file" icon.
func File(size string) templ.Component {
	return renderIcon(size, `<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/>`)
}

// FileText renders the Lucide "file-text" icon.
func FileText(size string) templ.Component {
	return renderIcon(size, `<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/>`)
}

// Filter renders the Lucide "filter" icon.
func Filter(size string) templ.Component {
	return renderIcon(size, `<polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/>`)
}

// Folder renders the Lucide "folder" icon.
func Folder(size string) templ.Component {
	return renderIcon(size, `<path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/>`)
}

// Github renders the Lucide "github" icon.
func Github(size string) templ.Component {
	return renderIcon(size, `<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/>`)
}

// Globe renders the Lucide "globe" icon.
func Globe(size string) templ.Component {
	return renderIcon(size, `<circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/>`)
}

// Heart renders the Lucide "heart" icon.
func Heart(size string) templ.Component {
	return renderIcon(size, `<path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/>`)
}

// Home renders the Lucide "home" icon.
func Home(size string) templ.Component {
	return renderIcon(size, `<path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/>`)
}

// Image renders the Lucide "image" icon.
func Image(size string) templ.Component {
	return renderIcon(size, `<rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/>`)
}

// Info renders the Lucide "info" icon.
func Info(size string) templ.Component {
	return renderIcon(size, `<circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>`)
}

// Key renders the Lucide "key" icon.
func Key(size string) templ.Component {
	return renderIcon(size, `<path d="m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4"/><path d="m21 2-9.6 9.6"/><circle cx="7.5" cy="15.5" r="5.5"/>`)
}

// LayoutGrid renders the Lucide "layout-grid" icon.
func LayoutGrid(size string) templ.Component {
	return renderIcon(size, `<rect width="7" height="7" x="3" y="3" rx="1"/><rect width="7" height="7" x="14" y="3" rx="1"/><rect width="7" height="7" x="14" y="14" rx="1"/><rect width="7" height="7" x="3" y="14" rx="1"/>`)
}

// Link renders the Lucide "link" icon.
func Link(size string) templ.Component {
	return renderIcon(size, `<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>`)
}

// List renders the Lucide "list" icon.
func List(size string) templ.Component {
	return renderIcon(size, `<line x1="8" x2="21" y1="6" y2="6"/><line x1="8" x2="21" y1="12" y2="12"/><line x1="8" x2="21" y1="18" y2="18"/><line x1="3" x2="3.01" y1="6" y2="6"/><line x1="3" x2="3.01" y1="12" y2="12"/><line x1="3" x2="3.01" y1="18" y2="18"/>`)
}

// Loader2 renders the Lucide "loader-2" icon.
func Loader2(size string) templ.Component {
	return renderIcon(size, `<path d="M21 12a9 9 0 1 1-6.219-8.56"/>`)
}

// Lock renders the Lucide "lock" icon.
func Lock(size string) templ.Component {
	return renderIcon(size, `<rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>`)
}

// LogIn renders the Lucide "log-in" icon.
func LogIn(size string) templ.Component {
	return renderIcon(size, `<path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/><polyline points="10 17 15 12 10 7"/><line x1="15" x2="3" y1="12" y2="12"/>`)
}

// LogOut renders the Lucide "log-out" icon.
func LogOut(size string) templ.Component {
	return renderIcon(size, `<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" x2="9" y1="12" y2="12"/>`)
}

// Mail renders the Lucide "mail" icon.
func Mail(size string) templ.Component {
	return renderIcon(size, `<rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/>`)
}

// MapPin renders the Lucide "map-pin" icon.
func MapPin(size string) templ.Component {
	return renderIcon(size, `<path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/>`)
}

// Menu renders the Lucide "menu" icon.
func Menu(size string) templ.Component {
	return renderIcon(size, `<line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/>`)
}

// MessageSquare renders the Lucide "message-square" icon.
func MessageSquare(size string) templ.Component {
	return renderIcon(size, `<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>`)
}

// Minus renders the Lucide "minus" icon.
func Minus(size string) templ.Component {
	return renderIcon(size, `<path d="M5 12h14"/>`)
}

// Moon renders the Lucide "moon" icon.
func Moon(size string) templ.Component {
	return renderIcon(size, `<path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>`)
}

// MoreHorizontal renders the Lucide "more-horizontal" icon.
func MoreHorizontal(size string) templ.Component {
	return renderIcon(size, `<circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/>`)
}

// MoreVertical renders the Lucide "more-vertical" icon.
func MoreVertical(size string) templ.Component {
	return renderIcon(size, `<circle cx="12" cy="12" r="1"/><circle cx="12" cy="5" r="1"/><circle cx="12" cy="19" r="1"/>`)
}

// Paperclip renders the Lucide "paperclip" icon.
func Paperclip(size string) templ.Component {
	return renderIcon(size, `<path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48"/>`)
}

// Pause renders the Lucide "pause" icon.
func Pause(size string) templ.Component {
	return renderIcon(size, `<rect width="4" height="16" x="6" y="4"/><rect width="4" height="16" x="14" y="4"/>`)
}

// Phone renders the Lucide "phone" icon.
func Phone(size string) templ.Component {
	return renderIcon(size, `<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/>`)
}

// Play renders the Lucide "play" icon.
func Play(size string) templ.Component {
	return renderIcon(size, `<polygon points="6 3 20 12 6 21 6 3"/>`)
}

// Plus renders the Lucide "plus" icon.
func Plus(size string) templ.Component {
	return renderIcon(size, `<path d="M5 12h14"/><path d="M12 5v14"/>`)
}

// Search renders the Lucide "search" icon.
func Search(size string) templ.Component {
	return renderIcon(size, `<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>`)
}

// Send renders the Lucide "send" icon.
func Send(size string) templ.Component {
	return renderIcon(size, `<path d="m22 2-7 20-4-9-9-4Z"/><path d="m22 2-11 11"/>`)
}

// Server renders the Lucide "server" icon.
func Server(size string) templ.Component {
	return renderIcon(size, `<rect width="20" height="8" x="2" y="2" rx="2" ry="2"/><rect width="20" height="8" x="2" y="14" rx="2" ry="2"/><line x1="6" x2="6.01" y1="6" y2="6"/><line x1="6" x2="6.01" y1="18" y2="18"/>`)
}

// Settings renders the Lucide "settings" icon.
func Settings(size string) templ.Component {
	return renderIcon(size, `<path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/>`)
}

// Shield renders the Lucide "shield" icon.
func Shield(size string) templ.Component {
	return renderIcon(size, `<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/>`)
}

// SortAsc renders the Lucide "sort-asc" icon.
func SortAsc(size string) templ.Component {
	return renderIcon(size, `<path d="m3 8 4-4 4 4"/><path d="M7 4v16"/><path d="M11 12h4"/><path d="M11 16h7"/><path d="M11 20h10"/>`)
}

// SortDesc renders the Lucide "sort-desc" icon.
func SortDesc(size string) templ.Component {
	return renderIcon(size, `<path d="m3 16 4 4 4-4"/><path d="M7 20V4"/><path d="M11 4h10"/><path d="M11 8h7"/><path d="M11 12h4"/>`)
}

// Square renders the Lucide "square" icon.
func Square(size string) templ.Component {
	return renderIcon(size, `<rect width="18" height="18" x="3" y="3" rx="2"/>`)
}

// Star renders the Lucide "star" icon.
func Star(size string) templ.Component {
	return renderIcon(size, `<polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>`)
}

// Sun renders the Lucide "sun" icon.
func Sun(size string) templ.Component {
	return renderIcon(size, `<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>`)
}

// Terminal renders the Lucide "terminal" icon.
func Terminal(size string) templ.Component {
	return renderIcon(size, `<polyline points="4 17 10 11 4 5"/><line x1="12" x2="20" y1="19" y2="19"/>`)
}

// Trash2 renders the Lucide "trash-2" icon.
func Trash2(size string) templ.Component {
	return renderIcon(size, `<path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/><line x1="10" x2="10" y1="11" y2="17"/><line x1="14" x2="14" y1="11" y2="17"/>`)
}

// Unlock renders the Lucide "unlock" icon.
func Unlock(size string) templ.Component {
	return renderIcon(size, `<rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 9.9-1"/>`)
}

// Upload renders the Lucide "upload" icon.
func Upload(size string) templ.Component {
	return renderIcon(size, `<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" x2="12" y1="3" y2="15"/>`)
}

// User renders the Lucide "user" icon.
func User(size string) templ.Component {
	return renderIcon(size, `<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>`)
}

// UserMinus renders the Lucide "user-minus" icon.
func UserMinus(size string) templ.Component {
	return renderIcon(size, `<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="22" x2="16" y1="11" y2="11"/>`)
}

// UserPlus renders the Lucide "user-plus" icon.
func UserPlus(size string) templ.Component {
	return renderIcon(size, `<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" x2="19" y1="8" y2="14"/><line x1="22" x2="16" y1="11" y2="11"/>`)
}

// Users renders the Lucide "users" icon.
func Users(size string) templ.Component {
	return renderIcon(size, `<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>`)
}

// Volume2 renders the Lucide "volume-2" icon.
func Volume2(size string) templ.Component {
	return renderIcon(size, `<polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><path d="M15.54 8.46a5 5 0 0 1 0 7.07"/><path d="M19.07 4.93a10 10 0 0 1 0 14.14"/>`)
}

// VolumeX renders the Lucide "volume-x" icon.
func VolumeX(size string) templ.Component {
	return renderIcon(size, `<polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><line x1="22" x2="16" y1="9" y2="15"/><line x1="16" x2="22" y1="9" y2="15"/>`)
}

// X renders the Lucide "x" icon.
func X(size string) templ.Component {
	return renderIcon(size, `<path d="M18 6 6 18"/><path d="m6 6 12 12"/>`)
}

// XCircle renders the Lucide "x-circle" icon.
func XCircle(size string) templ.Component {
	return renderIcon(size, `<circle cx="12" cy="12" r="10"/><path d="m15 9-6 6"/><path d="m9 9 6 6"/>`)
}

// Zap renders the Lucide "zap" icon.
func Zap(size string) templ.Component {
	return renderIcon(size, `<path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"/>`)
}

